// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Index → Botãos/Links*
 */
export interface IndexDocumentDataBotaosItem {
  /**
   * text field in *Index → Botãos/Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Veja meu portfólio
   * - **API ID Path**: index.botaos[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * link field in *Index → Botãos/Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: meusite
   * - **API ID Path**: index.botaos[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Index → link da rede social*
 */
export interface IndexDocumentDataRedesociaisItem {
  /**
   * text field in *Index → link da rede social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Github
   * - **API ID Path**: index.redesociais[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * link field in *Index → link da rede social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: github
   * - **API ID Path**: index.redesociais[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Index → footer*
 */
export interface IndexDocumentDataFooterItem {
  /**
   * text field in *Index → footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Feito com ❤️ pela
   * - **API ID Path**: index.footer[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * link field in *Index → footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Rocketseat
   * - **API ID Path**: index.footer[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type IndexDocumentDataSlicesSlice = never;

/**
 * Content for Index documents
 */
interface IndexDocumentData {
  /**
   * Imagem do Perfil field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Nome field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: @meunome
   * - **API ID Path**: index.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nome: prismic.KeyTextField;

  /**
   * Botãos/Links field in *Index*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index.botaos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  botaos: prismic.GroupField<Simplify<IndexDocumentDataBotaosItem>>;

  /**
   * link da rede social field in *Index*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index.redesociais[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redesociais: prismic.GroupField<Simplify<IndexDocumentDataRedesociaisItem>>;

  /**
   * footer field in *Index*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index.footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer: prismic.GroupField<Simplify<IndexDocumentDataFooterItem>>;

  /**
   * Slice Zone field in *Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>; /**
   * Meta Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

export type AllDocumentTypes = IndexDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataBotaosItem,
      IndexDocumentDataRedesociaisItem,
      IndexDocumentDataFooterItem,
      IndexDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
